### ISSUE TITLE
React support?

### ISSUE THREAD

**Issue by JunyWuuuu91** [dutiyesh/chrome-extension-cli#20]
want to create a react project by this cli, for `popup.html` or `options.html` eg.

**Comment by andey** [comment]
has anyone got react + babel to work?

i'm struggling to get babel to work for some reaosn.

````
Error in plugin "webpack-stream"
Message:
    Module parse failed: Unexpected token (5:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| ReactDOM.render(
>     <h1>Hello World</h1>,
|   document.getElementById('root')
| );
[21:42:04] 'background.js' errored after 253 ms
[21:42:04] TypeError: this.emit is not a function
    at Stream.<anonymous> (/Users/AndrewWei/Projects/realteasociety/node_modules/extension-cli/cli/gulpfile.js:56:18)
    at Stream.emit (node:events:539:35)
    at Stream.emit (node:domain:475:12)
    at callback (/Users/AndrewWei/Projects/realteasociety/node_modules/webpack-stream/index.js:189:16)
    at finalCallback (/Users/AndrewWei/Projects/realteasociety/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/AndrewWei/Projects/realteasociety/node_modules/webpack/lib/Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (/Users/AndrewWei/Projects/realteasociety/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/AndrewWei/Projects/realteasociety/node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (/Users/AndrewWei/Projects/realteasociety/node_modules/webpack/lib/Compiler.js:456:21)
    at /Users/AndrewWei/Projects/realteasociety/node_modules/webpack/lib/Compiler.js:1196:17
'default' errored after 259 ms
Build failed
```````

**Comment by kpripper** [comment]
Please add React to the library! Thank you!
Although the library is the best for developing extensions even without React.
