### ISSUE TITLE
Error Running npm run watch

### ISSUE THREAD

**Issue by mikeerickson** [dutiyesh/chrome-extension-cli#37]
Taking this for a quick spin and running into an error when running `npm run watch`

Node 14.5.0
Npm 7.16.0
macOS 12.6

```

[webpack-cli] HookWebpackError: Only file and data URLs are supported by the default ESM loader
    at makeWebpackError (/Users/mikee/Documents/code/litterbox/my-extension/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/mikee/Documents/code/litterbox/my-extension/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/mikee/Documents/code/litterbox/my-extension/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at /Users/mikee/Documents/code/litterbox/my-extension/node_modules/webpack/lib/Compilation.js:510:26
    at /Users/mikee/Documents/code/litterbox/my-extension/node_modules/copy-webpack-plugin/dist/index.js:708:13
-- inner error --
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:698:11)
    at Loader.resolve (internal/modules/esm/loader.js:82:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:226:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)
caused by plugins in Compilation.hooks.processAssets
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:698:11)
    at Loader.resolve (internal/modules/esm/loader.js:82:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:226:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)

```

**Comment by mikeerickson** [comment]
Tried using node 19.8 and all works as expected.
